---
title: "Airlines Customer Satisfactory"
output:
  pdf_document: default
  html_document: default
---

# Basic Setup

```{r cars}
rm(list = ls())
library(dplyr)
library(caret)
library(glmnet)
library(ROCR)
library(rpart)
library(rpart.plot)
library(ggplot2)
library(boot)
library(kknn)
library(caret)
library(tree)
library(ranger)
library(xgboost)
library(factoextra)

setwd("/Users/chenjieyi/Documents/GitHub/Airlines-Customer-Satisfactory")

data_train <- read.csv("train.csv")
data_train <- data_train[, c(-1, -2)]

data_test <- read.csv("test.csv")
data_test <- data_test[, c(-1, -2)]

for(i in 7:20){
  data_train <- data_train[data_train[,i] != 0,]
  data_test <- data_test[data_test[,i] != 0,]
}

data_train <- na.omit(data_train)
data_test <- na.omit(data_test)

```


```{r}
data_train <- mutate_if(data_train, is.character, as.factor)
data_test <- mutate_if(data_test, is.character, as.factor)
for(i in 7:20){
  data_train[,i] <- as.factor(data_train[,i])
  data_test[,i] <- as.factor(data_test[,i])
}
```


```{r}
fixNAs <- function(data_frame){
  # Define reactions to NAs
  integer_reac <- 0
  factor_reac <- "FIXED_NA"
  character_reac <- "FIXED_NA"
  date_reac <- as.Date("1900-01-01")
  
  # Loop through columns in the data frame 
  # and depending on which class the
  # variable is, apply the defined reaction and 
  # create a surrogate
  
  for (i in 1:ncol(data_frame)) {
    if (class(data_frame[,i]) %in% c("numeric","integer")) {
      if (any(is.na(data_frame[,i]))) {
        data_frame[,paste0(colnames(data_frame)[i],"_surrogate")] <-
          as.factor(ifelse(is.na(data_frame[,i]),"1","0"))
        data_frame[is.na(data_frame[,i]), i] <- integer_reac
      }
    } else
      if (class(data_frame[,i]) %in% c("factor")) {
        if (any(is.na(data_frame[,i]))){
          data_frame[,i]<-as.character(data_frame[,i])
          data_frame[,paste0(colnames(data_frame)[i],"_surrogate")] <-
            as.factor(ifelse(is.na(data_frame[,i]),"1","0"))
          data_frame[is.na(data_frame[,i]),i]<-factor_reac
          data_frame[,i]<-as.factor(data_frame[,i])
        }
      } else {
        if (class(data_frame[,i]) %in% c("character")) {
          if (any(is.na(data_frame[,i]))){
            data_frame[,paste0(colnames(data_frame)[i],"_surrogate")]<-
              as.factor(ifelse(is.na(data_frame[,i]),"1","0"))
            data_frame[is.na(data_frame[,i]),i]<-character_reac
          }
        } else {
          if (class(data_frame[,i]) %in% c("Date")) {
            if (any(is.na(data_frame[,i]))){
              data_frame[,paste0(colnames(data_frame)[i],"_surrogate")]<-
                as.factor(ifelse(is.na(data_frame[,i]),"1","0"))
              data_frame[is.na(data_frame[,i]),i]<-date_reac
            }
          }
        }
      }
  }
  
  return(data_frame)
}

data_train <- fixNAs(data_train)
data_test <- fixNAs(data_test)
```

```{r}
data_train <- data_train[,c(1:23)]
data_test <- data_test[,c(1:23)]
```


```{r}
data_train_cl1 <- data_train %>%
  mutate(Gender_2 = ifelse(Gender == "Male", 1, 0),
         Customer.Type_2 = ifelse(Customer.Type == "Loyal Customer", 1, 0),
         Type.of.Travel_2 = ifelse(Type.of.Travel == "Business travel", 1, 0),
         Class_2 = ifelse(Class == "Business", 2 , ifelse(Class == "Eco", 0, 1)),
         Satisfaction_2 = ifelse(satisfaction == "satisfied", 1, 0)) %>% 
  select(-c(Gender, Customer.Type, Type.of.Travel, Class, satisfaction))


set.seed(77)
cs2 <- kmeans(data_train_cl1, centers = 2, nstart = 100, iter.max = 100)
cs3 <- kmeans(data_train_cl1, centers = 3, nstart = 100, iter.max = 100)
cs4 <- kmeans(data_train_cl1, centers = 4, nstart = 100, iter.max = 100)
cs5 <- kmeans(data_train_cl1, centers = 5, nstart = 100, iter.max = 100)

data_train_cl2 <- data_train_cl1
for(i in 1:23){
  data_train_cl2[,i] <- as.numeric(data_train_cl2[,i])
  data_train_cl2[,i] <- as.numeric(data_train_cl2[,i])
}


ps1 <- fviz_cluster(cs2, geom = "point", data = data_train_cl2) + 
  ggtitle("k = 2")
ps2 <- fviz_cluster(cs3, geom = "point", data = data_train_cl2) + 
  ggtitle("k = 3")
ps3 <- fviz_cluster(cs4, geom = "point", data = data_train_cl2) + 
  ggtitle("k = 4")
ps4 <- fviz_cluster(cs5, geom = "point", data = data_train_cl2) + 
  ggtitle("k = 5")

gridExtra::grid.arrange(ps1, ps2, ps3, ps4, ncol = 2)
```


```{r}
set.seed(77)

cs22 <- kmeans(bb, centers = 2, nstart = 100, iter.max = 100)
cs33 <- kmeans(bb, centers = 3, nstart = 100, iter.max = 100)
cs44 <- kmeans(bb, centers = 4, nstart = 100, iter.max = 100)
cs55 <- kmeans(bb, centers = 5, nstart = 100, iter.max = 100)


ps11 <- fviz_cluster(cs22, geom = "point", data = bb) + ggtitle("k = 2")
ps22 <- fviz_cluster(cs33, geom = "point", data = bb) + ggtitle("k = 3")
ps33 <- fviz_cluster(cs44, geom = "point", data = bb) + ggtitle("k = 4")
ps44 <- fviz_cluster(cs55, geom = "point", data = bb) + ggtitle("k = 5")



gridExtra::grid.arrange(ps11, ps22, ps33, ps44, ncol = 2)

```


```{r}
cc <- bb %>% 
  select(Age, sex, customer.type, type.of.travel, class)


set.seed(77)

cs222 <- kmeans(cc, centers = 2, nstart = 1000, iter.max = 100)
cs333 <- kmeans(cc, centers = 3, nstart = 1000, iter.max = 100)
cs444 <- kmeans(cc, centers = 4, nstart = 1000, iter.max = 100)
cs555 <- kmeans(cc, centers = 5, nstart = 1000, iter.max = 100)


ps111 <- fviz_cluster(cs222, geom = "point", data = cc) + ggtitle("k = 2")
ps222 <- fviz_cluster(cs333, geom = "point", data = cc) + ggtitle("k = 3")
ps333 <- fviz_cluster(cs444, geom = "point", data = cc) + ggtitle("k = 4")
ps444 <- fviz_cluster(cs555, geom = "point", data = cc) + ggtitle("k = 5")



gridExtra::grid.arrange(ps111, ps222, ps333, ps444, ncol = 2)

```

```{r}
dd <- bb %>% 
  select(customer.type, type.of.travel, class)


set.seed(77)

cs2222 <- kmeans(dd, centers = 2, nstart = 1000, iter.max = 100)
cs3333 <- kmeans(dd, centers = 3, nstart = 1000, iter.max = 100)
cs4444 <- kmeans(dd, centers = 4, nstart = 1000, iter.max = 100)
cs5555 <- kmeans(dd, centers = 5, nstart = 1000, iter.max = 100)


ps1111 <- fviz_cluster(cs2222, geom = "point", data = dd) + ggtitle("k = 2")
ps2222 <- fviz_cluster(cs3333, geom = "point", data = dd) + ggtitle("k = 3")
ps3333 <- fviz_cluster(cs4444, geom = "point", data = dd) + ggtitle("k = 4")
ps4444 <- fviz_cluster(cs5555, geom = "point", data = dd) + ggtitle("k = 5")

gridExtra::grid.arrange(ps1111, ps2222, ps3333, ps4444, ncol = 2)
```





```{r}
datacs4 <- data_train

datacs4$cluster <- cs4444$cluster

ggplot(data = datacs4, aes(Type.of.Travel, fill = factor(cluster))) +
  geom_bar(position = "dodge2")

ggplot(data = datacs4, aes(Class, fill = factor(cluster))) +
  geom_bar(position = "dodge2")

ggplot(data = datacs4, aes(Customer.Type, fill = factor(cluster))) +
  geom_bar(position = "dodge2")



```



```{r}
ggplot(data = datacs4, aes(satisfaction, fill = factor(cluster))) +
  geom_bar(position = "dodge2")

ggplot(data = datacs4, aes(Inflight.wifi.service, fill = factor(cluster))) +
  geom_bar(position = "dodge2")

ggplot(data = datacs4, aes(Inflight.service, fill = factor(cluster))) +
  geom_bar(position = "dodge2")

ggplot(data = datacs4, aes(Online.boarding, fill = factor(cluster))) +
  geom_bar(position = "dodge2")


```


```{r}
datacs4 %>%
  count(cluster)
```


```{r}
datacs3 <- data_train

datacs3$cluster <- cs3333$cluster

ggplot(data = datacs3, aes(Type.of.Travel, fill = factor(cluster))) +
  geom_bar(position = "dodge2") +
  ggtitle("Type of Travel")
  
  


ggsave("Cluster: Type of Travel.png")


ggplot(data = datacs3, aes(Class, fill = factor(cluster))) +
  geom_bar(position = "dodge2") +
  ggtitle("Class distribution on each cluster")

ggsave("Class distribution on each cluster.png")

ggplot(data = datacs3, aes(Customer.Type, fill = factor(cluster))) +
  geom_bar(position = "dodge2") +
  ggtitle("Customer type on each cluster")

ggsave("Customer type on each cluster.png")
```


```{r}
ggplot(data = datacs3, aes(x = factor(cluster), fill = as.factor(satisfaction))) +
  geom_bar(stat = "count", position = "fill") +
  xlab("cluster") +
  guides(fill=guide_legend(title="satisfaction")) +
  ggtitle("Satisfaction distribution on each cluster")

ggsave("Satisfaction distribution on each cluster.png")

ggplot(data = datacs3, aes(x = factor(cluster), fill = as.factor(Inflight.wifi.service))) +
  geom_bar(stat = "count", position = "fill") +
  xlab("cluster") +
  guides(fill=guide_legend(title="Inflight.wifi.service")) +
  ggtitle("Inflight.wifi.service distribution on each cluster")

ggsave("Inflight.wifi.service.png")

ggplot(data = datacs3, aes(x = factor(cluster), fill = as.factor(Inflight.service))) +
  geom_bar(stat = "count", position = "fill") +
  xlab("cluster") +
  guides(fill=guide_legend(title="Inflight.service")) +
  ggtitle("Inflight.service distribution on each cluster")

ggsave("Inflight.service.png")
 
ggplot(data = datacs3, aes(x = factor(cluster), fill = as.factor(Online.boarding))) +
  geom_bar(stat = "count", position = "fill") +
  guides(fill=guide_legend(title="Online.boarding")) +
  xlab("cluster") +
   ggtitle("Online.boarding distribution on each cluster")

ggsave("Online.boarding distribution on each cluster.png")

```


